answer=ok&json=<?php echo urlencode(json_encode([
    'Store' => 'Store Items',
    //'Games' => 'Games',
    'divider' => '- - - - - - - - - - - -',
    'Early' => 'Early Poptropica',
    'Shark' => 'Shark Tooth',
    'Super' => 'Super Power',
    'Spy' => 'Spy',
    'Nabooti' => 'Nabooti',
    'BigNate' => 'Big Nate',
    'Astro' => 'Astro-Knights',
    'Counter' => 'Counterfeit',
    'Reality' => 'Reality TV',
    'Trade' => 'Skullduggery',
    'Steam' => 'Steamworks',
    'Peanuts' => 'Great Pumpkin',
    'Cryptid' => 'Cryptids',
    'West' => 'Wild West',
    'Wimpy' => 'Wimpy Wonderland',
    'Japan' => 'Red Dragon',
    'Train' => 'Mystery Train',
    'GameShow' => 'Game Show',
    'Ghost' => 'Ghost Story',
    'Shipwreck' => 'S.O.S.',
    'Vampire' => 'Vampire\'s Curse',
    'Woodland' => 'Twisted Thicket',
    'Charlie' => 'Chocolate Factory',
    'Boardwalk' => 'Wimpy Boardwalk',
    'Moon' => 'Lunar Colony',
    'Villain' => 'Super Villain',
    'Zombie' => 'Zomberry',
    'NightWatch' => 'Night Watch',
    'Backlot' => 'Back Lot'
    // Mini-quests? (Legendary Swords, Haunted House, etc.)
]));